### PR TITLE
Add tagspaces notation

### PR DESCRIPTION
**Pull request by jgru**
I added a  commandline switch named `--tagspaces` and the neccessary modifications to use a different notation for storing tags after the filename, which is compatible with the syntax used by the open source application [TagSpaces](https://github.com/tagspaces/tagspaces) for organizing and managing local files with the help of tags. 

I think it could be quite useful to combine the power of `filetags` and `TagSpaces`. 

Hope you like it!

Best regards 
jgru

### CODE REVIEW

**Comment by novoid** [comment]
Thanks @jgru for the pull request!

It really seems to add good stuff to filetags. However, before I merge it, I need to take some time and test it. This way, I am able to document what filetags features are working with the additional syntax and what features are not safe with TagSpaces syntax.

**Comment by jgru** [comment]
> 
> 
> Thanks @jgru for the pull request!
> 
> It really seems to add good stuff to filetags. However, before I merge it, I need to take some time and test it. This way, I am able to document what filetags features are working with the additional syntax and what features are not safe with TagSpaces syntax.

Thanks for the reply, @novoid . Please take all the time you need for testing, if I can do or fix something, let me know.

**Comment by rrottmann** [comment]
As a TagSpaces user I really like this feature and tested adding tags with Debian which worked great and Windows `cmd.exe` and `GitBash` which did not show the ASCII Art pre-filled with already existing tags:

```bash
# Windows 10
git clone https://github.com/jgru/filetags.git
cd filetags
git checkout remotes/origin/feature-tagspaces-notation
python --version
#Python 3.7.7
python -m venv
source venv\Scripts\activate
pip install -r requirements.txt
pip install pypiwin32
touch "some file.txt"
python filetags/__init__.py some*
# foo bar baz
ls -al some*
#-rw-r--r-- 1 rottmrei 197610 0 Jun 15 18:07 'some test -- foo bar baz.txt'
python filetags/__init__.py some\ test\ --\ foo\ bar\ baz.txt
#
#Please enter tags, separated by " "; abort with Ctrl-C; complete 3 tags with TAB
#
#         .----------------,
#        | o  bar baz foo  |
#         `----------------'
rm some*
touch "some file.txt"
python filetags/__init__.py --tagspaces some*
ls -al some*
#-rw-r--r-- 1 rottmrei 197610 0 Jun 15 18:11 'some test [foo bar baz].txt'
python filetags/__init__.py --tagspaces some\ test\ \[foo\ bar\ baz\].txt
#
#Please enter tags, separated by " "; abort with Ctrl-C
#
#         .--------,
#        | o   ?   |
#         `--------'
#
```
The tags are added correctly, though.

Also regarding the regular expression, one could use `re.escape()` to properly escape `FILENAME_PRE_TAG_SEPARATOR` and `FILENAME_POST_TAG_SEPARATOR`.

**Comment by novoid** [comment]
Hi @jgru ,
Way too long, that pull request is part of my todo list. I haven't forgotten, I just moved the many tasks for testing, thinking, potentially fixing, from week to week and month to month.

Hence this proposal: **how about you maintain a fork of filetags with support for TagSpaces?**

My reasoning should be explained:

I've got bad experience with https://github.com/novoid/Memacs/ where I added extension modules from other people to the project instead of linking them. This way, those modules could be found quite easily for users of Memacs. However, when somebody found an issue/bug within such a module, the fixing process was tedious or non-existent because I, myself, am not using those third-party modules in my workflows and therefore even setting up for bug confirmation would be much effort for myself.

I'm in a similar situation with the support for the TagSpaces syntax with filetags. I do not use it myself and I won't for the foreseeable future. I'm unsure if I am able to find all the edge-cases when testing and I do re-use filetags-like filenames in a lot of other tools which I won't extend for TagSpaces syntax. Therefore, users might get a wrong impression when assuming that filetags with support TagSpaces can be combined with my other tools that support this file name convention. Furthermore, I won't be able to provide too much effort in fixing TagSpace-related bugs and I'm afraid that you won't either here, with my experience from Memacs module authors (you might be different, of course). On the other hand side, a fork in your GitHub space would be the cleaner solution. Of course, I'd more than happy to link to your fork!

I don't know your thought on that. Maybe we can discuss this issue briefly here?

**Comment by jgru** [comment]
Hi @novoid ,

thanks for getting back to me and this dated PR. I can totally relate to your concerns. 
I will keep it as a fork, but won't offer maintenance of some form. 

Anyways, thanks for your work on filetags in general! 

Best regards,
jgru

**Comment by novoid** [comment]
Hi @jgru ,

Do you want me to link to your GitHub fork? Any particular wishes on the text?

If not, I wil add it to "Related Tools and Workflows" with "I you do prefer the https://www.tagspaces.org/ syntax for tags within filenames, you should check out the filetags fork on https://github.com/jgru/filetags".

**Comment by jgru** [comment]
> Hi @jgru ,
> 
> Do you want me to link to your GitHub fork? Any particular wishes on the text?
> 
> If not, I wil add it to "Related Tools and Workflows" with "I you do prefer the https://www.tagspaces.org/ syntax for tags within filenames, you should check out the filetags fork on https://github.com/jgru/filetags".

Hi @novoid, 

please keep it just in the related tools and workflows section, since I do not plan to provide any maintenance. 
Thanks. 

Best regards,
jgru

**Comment by novoid** [comment]
Done. Thanks for your effort - I know that your contribution was not trivial to implement! 🙇

**Pull request closed without merging**
